using WrapTuneMacOS.Signing;

namespace WrapTuneMacOS.Signing.Tests;

/// <summary>
/// End-to-end signing against the real <c>osslsigncode</c> binary, using a
/// throwaway self-signed cert generated by <c>openssl</c>. Self-skips (early
/// return — xUnit 2.x has no dynamic skip) when either tool is absent, mirroring
/// the engine's golden-fixture tests. Runs in CI once
/// <c>brew install osslsigncode</c> is added to the workflow.
/// </summary>
public sealed class PayloadSignerEndToEndTests
{
    [Fact]
    public async Task Signs_a_script_in_place_and_the_signature_is_detectable()
    {
        var ossl = SignerLocator.Locate();
        if (ossl is null) return;                          // osslsigncode not installed — skip.
        if (!await SigningTestEnv.HasOpenSslAsync()) return; // openssl not available — skip.

        var dir = Path.Combine(Path.GetTempPath(), "wt-sign-e2e-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var pfx = await SigningTestEnv.CreateSelfSignedPfxAsync(dir);

            var script = Path.Combine(dir, "install.ps1");
            await File.WriteAllTextAsync(script, "Write-Host 'hello from WrapTune'\n");

            var options = new SigningOptions
            {
                CertMode = CertMode.Pfx,
                PfxPath = pfx,
                Secret = SigningTestEnv.Password,
                TimestampUrl = null,   // no network dependency in the test
            };

            var signer = PayloadSigner.TryCreate(options, out var err);
            Assert.NotNull(signer);
            Assert.Null(err);

            var result = await signer!.SignAsync(dir, script, options);
            Assert.True(result.Success, result.Error);

            // osslsigncode verify must now find a signature on the file.
            var (_, vOut, vErr) = await ProcessRunner.RunAsync(ossl, ["verify", "-in", script]);
            Assert.DoesNotContain("No signature found", vOut + "\n" + vErr, StringComparison.OrdinalIgnoreCase);

            // Re-running must SKIP the now-signed file (don't clobber an existing signature).
            var rerun = await signer.SignAsync(dir, script, options);
            Assert.True(rerun.Success, rerun.Error);
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { /* best effort */ }
        }
    }
}
